server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: syslog

  pipeline_stages:
    - json:
        expressions:
          host: HOST_FROM
          priority: PRIORITY
          cisco_severity: cisco.severity
          message: MESSAGE
          timestamp: ISODATE
    - timestamp:
        format: RFC3339
        source: timestamp
    - labels:
        cisco_severity:
        host:
        priority:
    - output:
        source: message
  
  static_configs:
  - targets:
      - localhost
    labels:
      __path__: /var/log/fromcisco.log
      job: syslog


